categories:
  - developer
content: 'Setup you need to have to contribute to the guides & courses '
created: '2022-11-01T14:55:28.162Z'
guideIntegrations:
  discordRoleIds: []
guideType: onboarding
key: setup-dev-environment-dodao
name: Setup Dev Environment
publishStatus: Live
showIncorrectOnCompletion: true
steps:
  - content: >
      ### Type of Content

      In DoDAO we primarily write three type of contents

      1. Guides

      2. Courses

      3. Articles


      ### Contributing to guides and courses

      The best way to contribute towards creating or updating guides or courses
      is by editing the files in git repositories and then creating a pull
      request for reviews. This way, we can review the content that you write
      and make sure it meets our standards.
    name: Introduction
    stepItems: []
    uuid: aebdc966-5f62-4668-899c-9725c828741d
  - content: 'There are some pre-requisitis to be able to contribute effectively '
    name: Pre-requisites
    stepItems: []
    uuid: ab430e9e-fca3-4961-9f38-081c5bcd960a
  - content: >
      Any of the guides repositories like
      [https://github.com/DoDAO-io/dodao-academy-guides](https://github.com/DoDAO-io/dodao-academy-guides)
      have the following structure.

      ```

      |--- LICENSE

      |--- README.md

      |--- aa.txt

      |--- generated

      |     |--- json

      |     |     |--- guide-file-1.json

      |     |     |--- guide-file-2.json

      |     |     |--- guides.json

      |     |--- markdown

      |         |--- guide-file-1.md

      |         |--- guide-file-1.md

      |--- package.json

      |--- src

      |     |--- guide-file-1.yaml

      |     |--- guide-file-2.yaml

      |     |--- guides-footer.md

      |     |--- guides-header.md

      |     |--- guides.yaml

      |--- yarn.lock


      ```

      Important things to keep in mind are 

      1. All the content to be added or updated needs to be written in `yaml`
      files i.e. under `src` directory

      2. All the files under `generated` directory are the files generated from
      the yaml files after we run `yarn test`

      3. Files under `generated/json` are used by the app to render guides in
      the browser

      4. Files under `generated/markdown` can be used by you to check the
      formatting of the content

      5. Before you create a pull request, make sure to run `yarn test` and also
      checkin the generated files.
    name: Guide Repo Structure
    stepItems: []
    uuid: 605385c5-b709-4170-b429-40604557717c
  - content: |-
      ```
      .
      |--- LICENSE
      |--- README.md
      |--- aa.txt
      |--- generated
      |   |--- course.json
      |   |--- explanations
      |   |      |--- aave-smart-contracts.md
      |   |--- questions
      |   |      |--- aave-smart-contracts.md
      |   |--- readings
      |   |      |--- aave-smart-contracts.md
      |   |--- summaries
      |   |      |--- aave-smart-contracts.md
      |   |--- topics
      |          |--- aave-smart-contracts.md
      |--- images
      |   |--- aave.jpg
      |   |--- architechture.png
      |--- package-lock.json
      |--- package.json
      |--- src
      |   |--- course-header.md
      |   |--- course.yaml
      |   |--- explanations
      |   |      |--- aave-smart-contracts.yaml
      |   |--- questions
      |   |      |--- aave-smart-contracts.yaml
      |   |--- readings
      |   |      |--- aave-smart-contracts.yaml
      |   |--- summaries
      |          |--- aave-smart-contracts.yaml
      |--- yarn.lock
      ```
    name: Course Repo Structure
    stepItems: []
    uuid: e8951921-87e4-444c-b199-820e9012241a
thumbnail: >-
  https://d31h13bdjwgzxs.cloudfront.net/QmWy8EeMnxqx96VEPx2NBwzqtKxvMQqVVYvmPKgAYS2cUi
uuid: setup-dev-environment-dodao
